name: Program Analysis and Compilation Group at MIT CSAIL
url: http://pac.mit.edu

exclude: [bibble, README.md, Makefile]

# colorize code snippets with the pygments module
highlighter: pygments

# Sections on the "people" page.
roles:
    - {key: faculty, name: Faculty}
    - {key: grad, name: Graduate Students}
    - {key: postdoc, name: Post-Doctoral Fellows}
    - {key: scientist, name: Research Scientists}
    - {key: alum, name: Alumni}

# Base pathname for links.
base: ''

# Navigation bar links.
navigation:
    - title: Home
      link: /
    - title: Publications
      link: /publications.html
